### ISSUE TITLE
multiple fixes need a real Python programmer to do right

### ISSUE THREAD

**Issue by idallen** [JohnTheNerd/PySarra#9]
I am not a Python programmer.  Someone who knows Python should do these changes properly.
Attached is a `diff -u` of my changes:  [diff.txt](https://github.com/user-attachments/files/18092967/diff.txt)
Summary of changes in the diff:

I added an `on_open_error_callback` method to `SelectConnection` that 
sleeps 60 seconds and then tries to reconnect, up to 60 times (one hour).
This eliminates the useless traceback on a connection error.

I added processor `message` field names `filename` and `url` as decoded 
strings and made the regex match only on the `filename` and not on the
whole URL. 

I insert a missing slash between the host name and the file name in the
`url` if it is missing (and it was for a while).  The `message` field
is unchanged, and may be missing the slash (and it was for a while).

I added `=None` to some final parameters on some callbacks so that 
missing parameters don't trigger an exception.

I trap the failure to reconnect in `on_connection_closed` and just exit 
the program.  Someone should get the reconnection to work properly.

**Comment by JohnTheNerd** [comment]
it appears that these all occurred from changes at the library level - according to [their example](https://github.com/pika/pika/blob/main/examples/asynchronous_consumer_example.py) many of the function definitions have changed. I'm working on a refactor that should close this issue and all others.

**Comment by JohnTheNerd** [comment]
my current work can be found in the branch named `simplify-codebase` - which includes the changes above alongside a massive simplification of the codebase (main.py is merely 115 lines now).

I intentionally did not implement the re-tries for very long (merely 5 retries with 60 second sleeps in-between), as I believe retries should not be PySarra's responsibility - we have lots of great tools like supervisord, zookeeper, systemd, etc for that. it will now also fail completely after 5 retries, in order to alert those tools that something went wrong.

**Comment by JohnTheNerd** [comment]
fixed by #10
